### ISSUE TITLE
Azure event bus fails if the namespace length is less than 6

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-incubator/compass#1013]
**Description**

Azure evnet hub fails with following message
`Error occured: Failed to persist Azure EventHubs Namespace [rg-38] with error: eventhub.NamespacesClient#CreateOrUpdate: Invalid input: autorest/validation: validation failed: parameter=namespaceName constraint=MinLength value=\"rg-38\" details: value length must be greater than or equal to 6, Retrying for 30m0s in 1m0s steps" instanceID=rg-38 operation=628725fb-e65b-41a0-a7a7-7a1a5d6eb3ca step="Provision Azure Event Hubs"`

**Comment by nachtmaar** [comment]
In this case retrying really makes no sense. We should do validation on the name which is based on the provisioning parameters name, in the http put call to KEB. Moreover, we should print the error which causes the retry [here](https://github.com/kyma-incubator/compass/blob/b0fcdff99d61381abe2782c7e95f7415cb6bc74e/components/kyma-environment-broker/internal/process/operation.go#L64). Otherwise the error will only be shown after the last retry. @rakesh-garimella already did it in the above log line.
