### ISSUE TITLE
Improve GraphQL input validation

### ISSUE THREAD

**Issue by pkosiec** [kyma-incubator/compass#255]
**Description**

Currently we have very limited validation for inputs.
For example, some fields are required, but still user could provide empty string. There should be consistent approach for every input.

- Investigate what we should validate
- Validate strings that are required and shouldn't be empty
- Validate URLs - We can use URI type extension for PostgreSQL or some kind of validator https://github.com/petere/pguri.
- Validate application names (like length etc.)
- create a ticket with solution for validatipon/conversion specs values. (assign to next release)

Complexity level: high

**Reasons**

It is crucial to block incorrect user input to assure everything (agent, integrations, etc.) works properly.

**Comment by tgorgol** [comment]
Now that we support XML SpecFormat (used by OData) we could validate if provided spec type (OData, OpenAPI, AsyncAPI) and spec format (XML, JSON, YAML) are correct (for example, we could return error if someone tries to create spec of type OpenAPI with XML format).

**Comment by tgorgol** [comment]
## Proposed validation library

https://github.com/go-playground/validator - in this library developer uses struct tags to define validation rules. It is possible to define custom rules or struct validation rules. Validator instance caches struct info, so it has to be passed as dependency (a single instance of validator could be constructed in root resolver and passed to services.

## Proposed validation rules for Compass input types

### APIDefinitionInput

Field | Rules (validation tags) | Comment
-- | -- | --
name: String! | required |  
description: String |   |  
targetURL: String! | required,url |  
group: String |   |  
spec: APISpecInput |   | ODATA works with XML and JSON<br>OPEN_API works with YAML and JSON
version: VersionInput |   |  
defaultAuth: AuthInput |   |  

### APISpecInput

Field | Rules (validation tags) | Comment
-- | -- | --
data: CLOB (string) |   |  
type: APISpecType! | required,oneof=ODATA OPEN_API |  
format: SpecFormat! | required,oneof=YAML JSON XML |  
fetchRequest: FetchRequestInput |   |  

### EventAPIDefinitionInput

Field | Rules (validation tags) | Comment
-- | -- | --
name: String! | required |  
description: String |   |  
spec: EventAPISpecInput! | required | ASYNC_API works with YAML and JSON
group: String |   |  
version: VersionInput |   |  

### EventAPISpecInput

Field | Rules (validation tags) | Comment
-- | -- | --
data: CLOB (string) |   |  
eventSpecType: EventAPISpecType! | required,oneof=ASYNC_API |  
format: SpecFormat! | required,oneof=YAML JSON |  
fetchRequest: FetchRequestInput |   |  

### VersionInput

Field | Rules (validation tags) | Comment
-- | -- | --
value: String! | required |
deprecated: Boolean = false | required |
deprecatedSince: String | |
forRemoval: Boolean = false | required |

### ApplicationCreateInput

Field | Rules (validation tags) | Comment
-- | -- | --
name: String! | required,max=36 | Requirement comes from frogs as they need to be able to append some suffix to name
description: String |   |  
labels: Labels (map[string]interface{}) |   |  
webhooks: [WebhookInput!] | dive,required |  
healthCheckURL: String | url |  
apis: [APIDefinitionInput!] | dive,required |  
eventAPIs: [EventAPIDefinitionInput!] | dive,required |  
documents: [DocumentInput!] | dive,required |  

### ApplicationUpdateInput

Field | Rules (validation tags) | Comment
-- | -- | --
name: String! | required,max=36 | Requirement comes from frogs as they need to be able to append some suffix to name
description: String |   |  
healthCheckURL: String | url |  

### RuntimeInput

Field | Rules (validation tags) | Comment
-- | -- | --
name: String! | required |
description: String | |
labels: Labels (map[string]interface{}) | |

### IntegrationSystemInput

Field | Rules (validation tags) | Comment
-- | -- | --
name: String! | required |  
description: String |   |  

### DocumentInput

Field | Rules (validation tags) | Comment
-- | -- | --
title: String! | required |  
displayName: String! | required |  
description: String! | required |  
format: DocumentFormat! | required,oneof=MARKDOWN |  
kind: String |   |  
data: CLOB (string) |   |  
fetchRequest: FetchRequestInput |   |  

### WebhookInput

Field | Rules (validation tags) | Comment
-- | -- | --
type: ApplicationWebhookType! | required |
url: String! | required,url |
auth: AuthInput | |

### LabelDefinitionInput

Field | Rules (validation tags) | Comment
-- | -- | --
key: String! | required |  
schema: JSONSchema (string) |   |  

### FetchRequestInput

Field | Rules (validation tags) | Comment
-- | -- | --
url: String! | required,url |  
auth: AuthInput |   |  
mode: FetchMode = SINGLE | required,oneof=SINGLE PACKAGE INDEX | required because has default value (?)
filter: String |   |  

### AuthInput

Field | Rules (validation tags) | Comment
-- | -- | --
credential: CredentialDataInput! | required |  
additionalHeaders: HttpHeaders (map[string][]string) |   |  
additionalQueryParams: QueryParams (map[string][]string) |   |  
requestAuth: CredentialRequestAuthInput |   | Exactly one not nil

### CredentialDataInput

Field | Rules (validation tags) | Comment
-- | -- | --
basic: BasicCredentialDataInput |   |  
oauth: OAuthCredentialDataInput |   |  

### BasicCredentialDataInput

Field | Rules (validation tags) | Comment
-- | -- | --
username: String! | required |  
password: String! | required |  

### OAuthCredentialDataInput

Field | Rules (validation tags) | Comment
-- | -- | --
clientId: ID! | required |
clientSecret: String! | required |
url: String! | required |

### CredentialRequestAuthInput

Field | Rules (validation tags) | Comment
-- | -- | --
csrf: CSRFTokenCredentialRequestAuthInput |   |  

### CSRFTokenCredentialRequestAuthInput

Field | Rules (validation tags) | Comment
-- | -- | --
tokenEndpointURL: String! | required |  
credential: CredentialDataInput! | required | Exactly one not nil
additionalHeaders: HttpHeaders (map[string][]string) |   |  
additionalQueryParams: QueryParams (map[string][]string) |   |
