### ISSUE TITLE
Implementation for secure resolvers

### ISSUE THREAD

**Issue by dbadura** [kyma-incubator/compass#420]
**Description**

Implement proposal introduced in https://github.com/kyma-incubator/compass/blob/master/docs/internal/investigations/secure-resolvers/secure-resolvers.md

**AC**
- Implement directive `limitAccessFor` @dbadura 
- Implement `limitManagerAccessTo` directive @pkosiec 
- Update scopes

**AC**
- To be defined when proposal will be accepted
- Add test e2e 
- Add docs for all directives - describe it quickly in architecture docs

**Reasons**

**Comment by dbadura** [comment]
Probably we can use the directive on field, but we need to update `gqlgen` to version **0.9.1**

**Comment by dbadura** [comment]
Investigate if in new vesion of `gqlgen` we can use this directive on argument.

**Comment by aszecowka** [comment]
Our security model seems to be more demanding than we thought, and it seems that we cannot properly protect our resources using only directives.
Let assume simple example, of `updateApplication` mutation.
This mutation can be executed by:
- user - if a user has required scopes, and user works in the same tenant as the application, then mutation can be executed
- runtime - cannot execute mutation, and this will be blocked by missing scopes
- integration system - if an application has set `integrationSystemID`, then only integration system that matches `integrationSystemID` can execute mutation. That means that we have to fetch from database given Application, because we need to access `integrationSystemID`. Probably, if integationSystemID is specfied, Application cannot edit itself.
- application, if `integrationSystemID` is not provided, then we need to check if application tries to updates itself and not to update data for other application.

**Comment by pkosiec** [comment]
> But internally, we have to fetch parent root object and check if the client (user, runtime, integration system, application) can perform this request. We have to ensure, that ApplicationA, cannot update the webhook for ApplicationB.

It's also worth noting that currently our mutations for webhook, document, API, Event Definitions (like delete) doesn't check parent ID (Application ID), so even if we go for directives, we still need to modify these services.

> In addition to that, we should think about permissions for labeling, especially for setting SCENARIO label.

There is already an issue for that: https://github.com/kyma-incubator/compass/issues/430

**Comment by aszecowka** [comment]
Questions from our workshop:
> Can Integration System changes Application.IntegrationSystemID to point to another Integration System?
> Can Integration System registers Application Template for another Integration System?

Will it be solved by this issue?

**Comment by pkosiec** [comment]
We will reevaluate this topic: https://github.com/kyma-incubator/compass/issues/1301
