### ISSUE TITLE
Make Provisioner able to create standalone Kyma clusters

### ISSUE THREAD

**Issue by Maladie** [kyma-incubator/compass#703]
**Description**

In the current flow, Provisioner creates cluster, installs Kyma with Runtime Agent and configures newly created Runtime to connect to Director. We should make Runtime Agent and Runtime configuration optional, so the user can create standalone Kyma clusters.

**Acceptance criteria**:
- Installation of Compass Runtime Agent is optional
- Creation of Config Map with runtime configuration is optional

**Comment by janmedrek** [comment]
Since the Provisioner is a part of the MPS ecosystem there will most probably no need to provision stand-alone Kyma instances via this component. Provisioner works closely with the Director and Kyma Environment Broker. This will not be worked on, perhaps with the bigger shift to the whole ecosystem this issue should be revisited.
