### ISSUE TITLE
Schedules backups for runtimes

### ISSUE THREAD

**Issue by janmedrek** [kyma-incubator/compass#751]
**Description**

A periodic backup for a Kyma runtime provisioned by compass based on the Kyma backup module is required.
For that, a storage bucket needs to get created in every tenant account and the runtime needs to get configured accordingly.

![backup](https://user-images.githubusercontent.com/7479371/75427213-5f51ca80-5946-11ea-8456-22b7825fb3ee.png)

In order to prepare the bucket and have a proper installer overwrite for a provisioning request, a KEB step need to be implemented covering the following points
1. Create bucket
  - in a different zone then the cluster
  - have encryption enabled
  - have data retention of 30days
  - have audit logs enabled for read access even
  - restrict access so that a user with general read permission cannot access i
2. Create service account which has permission to write backups and create snapshot of the volumes
3. Create folder in bucket with cluster UUID in folder name, label folder as well (not sure if needed)
4. Generate proper override for installer
  - leveraging the created service account
  - having a scheduled daily backup enabled

**Acceptance Criteria**
- Scheduled backup is active in provisioned runtime
- Restore is tested with a backup coming from new setup. Test setup was with applications defined in compass and mapped to the runtime
- Document personal data handling (where by what, retention, offboarding)
- Figure out prizing over one month

**Notes**
- It might be helpful to upgrade velero to latest beta version in order to improve the restore process: 
https://github.com/kyma-project/kyma/issues/7372

- The step framework is implemented by https://github.com/kyma-incubator/compass/issues/816
- The account pool gets integrated to KEB here: https://github.com/kyma-incubator/compass/pull/565
It will provide an AccountProvider interface to be used within a step

- Advantage of storing the backups with the customer cluster (versus having it in a central project) is:
  - billing of the backups is clearly assignable
  - every cluster (or at least all clusters of a customer) should have it's own service account with limited rights to access the backups. In a central managed project you need to manage the big list of acounts as well together with our other accounts.
  - it is assured that a customer cannot access the data of another customer

**Comment by a-thaler** [comment]
We decided to drop the topic for now as it exposed several challenges.
1. Velero requires a ServicePrincipal in order to create volume snapshots. That principal must be dedicated for that backup scenario with limited permissions to the cloud project.
2. Requesting and populating such second principal into the environment broker is not trivial and a big investment
3. The restore itself will be a complex process which is not stable enough as the restore phase of a full kyma cluster with velero is flaky
4. The restore requires a new cluster which then gets mapped to the old DNS, which is currently not possible using the gardener internal domains as they are sticky to shoot clusters.
